---

name: "❌ Bug"
about: 버그 발생시 사용해주세요
title: "[Bug]"
labels: ''
assignees: ''
body:

- type: textarea
  attributes:
  label: 🐞 버그 설명
  description: 버그에 대한 설명을 작성해 주세요.
  validations:
  required: true
- type: textarea
  attributes:
  label: ✅ 예상 결과
  description: 예상한 결과를 작성해 주세요.
  validations:
  required: true
- type: textarea
  attributes:
  label: ❗ 실제 결과
  description: 실제로 발생한 결과를 작성해 주세요.
  validations:
  required: true
- type: textarea
  attributes:
  label: 🧾 로그
  description: 로그가 있으면 복붙해 주세요.
  render: shell
  validations:
  required: false
